{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d90a6ac4-1915-45a8-a16f-62c059eeb52d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "agents/manuel_article_generation/agent.py\n",
    "──────────────────────────────\n",
    "Article Generation Agent \n",
    "───────────────────\n",
    "Responsabilidad: Escribe articulos cortos, amigables con piezas optimizadas para generar visibilidad y engagement.\n",
    "\n",
    "Arquitectura:\n",
    "    Usuario / Orchestrator\n",
    "          │\n",
    "          ▼\n",
    "    manuel_article_generation.run(query)\n",
    "          │\n",
    "          ├─► KnowledgeBase.retrieve()   ← ChromaDB local\n",
    "          ├─► web_search()               ← Google CSE o mock\n",
    "          ├─► get_trending_topics()      ← pytrends o mock\n",
    "          └─► Gemini generate_content()  ← google-genai (Vertex AI)\n",
    "                    │\n",
    "                    └─► Respuesta estructurada (ArticleIdea[])\n",
    "\n",
    "Dependencias:\n",
    "    pip install google-genai chromadb pytrends requests\n",
    "\n",
    "Uso local (sin GCloud):\n",
    "    Configurar GEMINI_API_KEY en .env con una key de AI Studio.\n",
    "    Vertex AI se activa automáticamente cuando se detecte PROJECT_ID.\n",
    "\"\"\"\n",
    "\n",
    "from __future__ import annotations\n",
    "\n",
    "import json\n",
    "import os\n",
    "from dataclasses import dataclass, field\n",
    "from typing import Any\n",
    "\n",
    "# ── Google GenAI SDK ──────────────────────────────────────────────────────────\n",
    "from google import genai\n",
    "from google.genai import types\n",
    "\n",
    "# ── Módulos internos ──────────────────────────────────────────────────────────\n",
    "import sys\n",
    "sys.path.insert(0, os.path.join(os.path.dirname(__file__), \"..\", \"..\"))\n",
    "\n",
    "from core.vector_store import VectorStore\n",
    "from core.memory import Memory\n",
    "from core.chunker import chunk_document\n",
    "from tools.search_tools import (\n",
    "    web_search,\n",
    "    get_trending_topics,\n",
    "    score_local_relevance,\n",
    "    TOOL_SCHEMAS,\n",
    "    TOOL_DISPATCH,\n",
    ")\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Config\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "GEMINI_API_KEY = os.getenv(\"GEMINI_API_KEY\", \"\")      \n",
    "VERTEX_PROJECT  = os.getenv(\"GOOGLE_CLOUD_PROJECT\", \"\") \n",
    "VERTEX_REGION   = os.getenv(\"GOOGLE_CLOUD_REGION\", \"us-central1\")\n",
    "\n",
    "CHAT_MODEL      = os.getenv(\"CHAT_MODEL\", \"gemini-2.0-flash\")\n",
    "MAX_OUTPUT_TOKENS = 4096\n",
    "TEMPERATURE       = 0.4\n",
    "\n",
    "\n",
    "def _build_client() -> genai.Client:\n",
    "    \"\"\"\n",
    "    Prioridad de autenticación:\n",
    "    1. Vertex AI (si hay PROJECT_ID en env) → producción\n",
    "    2. GEMINI_API_KEY                        → desarrollo local\n",
    "    \"\"\"\n",
    "    if VERTEX_PROJECT:\n",
    "        return genai.Client(\n",
    "            vertexai=True,\n",
    "            project=VERTEX_PROJECT,\n",
    "            location=VERTEX_REGION,\n",
    "        )\n",
    "    if GEMINI_API_KEY:\n",
    "        return genai.Client(api_key=GEMINI_API_KEY)\n",
    "    raise EnvironmentError(\n",
    "        \"Configura GEMINI_API_KEY (local) o GOOGLE_CLOUD_PROJECT (Vertex AI).\"\n",
    "    )\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Modelos de datos de salida\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "@dataclass\n",
    "class ArticleIdea:\n",
    "    title: str\n",
    "    angle: str                          # enfoque periodístico sugerido\n",
    "    category: str                       # política, deportes, cultura…\n",
    "    local_relevance_score: float        # 0–1\n",
    "    sources: list[str] = field(default_factory=list)\n",
    "    keywords: list[str] = field(default_factory=list)\n",
    "    priority: str = \"media\"             # alta / media / baja\n",
    "\n",
    "    def to_dict(self) -> dict:\n",
    "        return self.__dict__\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class ResearchReport:\n",
    "    query: str\n",
    "    trending_topics: list[str]\n",
    "    article_ideas: list[ArticleIdea]\n",
    "    context_snippets: list[str]         # fragmentos RAG usados\n",
    "    raw_web_results: list[dict]\n",
    "\n",
    "    def to_dict(self) -> dict:\n",
    "        return {\n",
    "            \"query\":            self.query,\n",
    "            \"trending_topics\":  self.trending_topics,\n",
    "            \"article_ideas\":    [a.to_dict() for a in self.article_ideas],\n",
    "            \"context_snippets\": self.context_snippets,\n",
    "        }\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# Knowledge Base (RAG)\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "class KnowledgeBase:\n",
    "    \"\"\"\n",
    "    Indexa documentos del periódico (artículos históricos, estilo, contexto)\n",
    "    y los recupera semánticamente para enriquecer las respuestas del agente.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, persist_dir: str = \"data/embeddings\"):\n",
    "        self._store = VectorStore(\n",
    "            collection_name=\"news_research\",\n",
    "            persist_dir=persist_dir,\n",
    "        )\n",
    "\n",
    "    def add_document(self, doc: dict) -> None:\n",
    "        \"\"\"\n",
    "        doc = {\"title\": ..., \"date\": ..., \"category\": ..., \"content\": ...}\n",
    "        \"\"\"\n",
    "        chunks = chunk_document(doc)\n",
    "        texts = [c[\"text\"] for c in chunks]\n",
    "        metas = [{k: v for k, v in c.items() if k != \"text\"} for c in chunks]\n",
    "        self._store.upsert(texts=texts, metadatas=metas)\n",
    "\n",
    "    def add_documents(self, docs: list[dict]) -> None:\n",
    "        for doc in docs:\n",
    "            self.add_document(doc)\n",
    "\n",
    "    def retrieve(self, query: str, top_k: int = 4) -> list[str]:\n",
    "        results = self._store.query(query, top_k=top_k)\n",
    "        return [r.text for r in results]\n",
    "\n",
    "    def count(self) -> int:\n",
    "        return self._store.count()\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "# News Research Agent\n",
    "# ─────────────────────────────────────────────────────────────────────────────\n",
    "\n",
    "class NewsResearchAgent:\n",
    "    \"\"\"\n",
    "    Agente de investigación de noticias.\n",
    "\n",
    "    Flujo de .run(query):\n",
    "    ┌─────────────────────────────────────────────────────────────┐\n",
    "    │ 1. Recuperar contexto histórico del periódico (RAG)         │\n",
    "    │ 2. Obtener trending topics locales                          │\n",
    "    │ 3. Buscar noticias recientes en la web                      │\n",
    "    │ 4. Enviar todo a Gemini con system prompt especializado      │\n",
    "    │ 5. Parsear respuesta → ResearchReport                       │\n",
    "    └─────────────────────────────────────────────────────────────┘\n",
    "    \"\"\"\n",
    "\n",
    "    SYSTEM_PROMPT = \"\"\"\n",
    "Eres José el News Research Agent de un periódico local.\n",
    "Tu misión: investigar tendencias, detectar oportunidades de cobertura y\n",
    "proponer ideas de artículos periodísticos relevantes para la comunidad local.\n",
    "\n",
    "PERSONALIDAD:\n",
    "- Curioso, analítico y orientado a la comunidad\n",
    "- Buscas siempre el ángulo local de cada noticia nacional o global\n",
    "- Priorizas historias con impacto directo en la vida de los vecinos\n",
    "- Siempre buscas al menos 2 fuentes similares antes de proponer una noticia\n",
    "\n",
    "RESTRICCIONES:\n",
    "- Nunca inventes datos o fuentes específicas; si no tienes información, dilo\n",
    "- No cubras temas fuera del ámbito periodístico local\n",
    "- Prioriza la verificabilidad de la información\n",
    "\n",
    "FORMATO DE SALIDA:\n",
    "Cuando se te pida proponer ideas, responde SIEMPRE con JSON válido:\n",
    "{\n",
    "  \"article_ideas\": [\n",
    "    {\n",
    "      \"title\": \"Título sugerido del artículo\",\n",
    "      \"angle\": \"Enfoque o ángulo periodístico específico\",\n",
    "      \"category\": \"política|deportes|cultura|economía|sucesos|comunidad\",\n",
    "      \"local_relevance_score\": 0.0,\n",
    "      \"sources\": [\"fuente1\", \"fuente2\"],\n",
    "      \"keywords\": [\"keyword1\", \"keyword2\"],\n",
    "      \"priority\": \"alta|media|baja\"\n",
    "    }\n",
    "  ],\n",
    "  \"summary\": \"Resumen ejecutivo del panorama informativo actual\"\n",
    "}\n",
    "\"\"\".strip()\n",
    "\n",
    "    def __init__(\n",
    "        self,\n",
    "        knowledge_base: KnowledgeBase,\n",
    "        memory: Memory | None = None,\n",
    "        newspaper_name: str = \"La gazeta local\",\n",
    "        region: str = \"ES\",\n",
    "    ):\n",
    "        self.kb = knowledge_base\n",
    "        self.memory = memory or Memory(max_turns=10)\n",
    "        self.newspaper_name = newspaper_name\n",
    "        self.region = region\n",
    "        self._client = _build_client()\n",
    "\n",
    "    # ── Método principal ──────────────────────────────────────────────────────\n",
    "\n",
    "    def run(self, query: str) -> ResearchReport:\n",
    "        \"\"\"\n",
    "        Ejecuta el ciclo completo de investigación.\n",
    "\n",
    "        Args:\n",
    "            query: Tema o pregunta de investigación.\n",
    "                   Ej: \"¿Qué pasa con el transporte público esta semana?\"\n",
    "\n",
    "        Returns:\n",
    "            ResearchReport con ideas de artículos estructuradas.\n",
    "        \"\"\"\n",
    "        # 1. RAG: contexto histórico del periódico\n",
    "        context_snippets = self.kb.retrieve(query, top_k=4)\n",
    "\n",
    "        # 2. Trending topics\n",
    "        trending = get_trending_topics(region=self.region)\n",
    "\n",
    "        # 3. Búsqueda web\n",
    "        web_results = web_search(query, num_results=5)\n",
    "\n",
    "        # 4. Construir prompt enriquecido\n",
    "        user_prompt = self._build_prompt(\n",
    "            query=query,\n",
    "            context_snippets=context_snippets,\n",
    "            trending=trending,\n",
    "            web_results=web_results,\n",
    "        )\n",
    "\n",
    "        # 5. Llamar a Gemini\n",
    "        self.memory.add(\"user\", user_prompt)\n",
    "\n",
    "        response = self._client.models.generate_content(\n",
    "            model=CHAT_MODEL,\n",
    "            contents=self._messages_to_contents(self.memory.as_messages()),\n",
    "            config=types.GenerateContentConfig(\n",
    "                system_instruction=self._personalized_system_prompt(),\n",
    "                max_output_tokens=MAX_OUTPUT_TOKENS,\n",
    "                temperature=TEMPERATURE,\n",
    "            ),\n",
    "        )\n",
    "\n",
    "        raw_text = response.candidates[0].content.parts[0].text\n",
    "        self.memory.add(\"model\", raw_text)\n",
    "\n",
    "        # 6. Parsear respuesta\n",
    "        article_ideas = self._parse_ideas(raw_text)\n",
    "\n",
    "        return ResearchReport(\n",
    "            query=query,\n",
    "            trending_topics=trending,\n",
    "            article_ideas=article_ideas,\n",
    "            context_snippets=context_snippets,\n",
    "            raw_web_results=web_results,\n",
    "        )\n",
    "\n",
    "    def chat(self, user_input: str) -> str:\n",
    "        \"\"\"\n",
    "        Modo conversacional libre (sin parseo estructurado).\n",
    "        Útil para el Reader Interaction Agent o pruebas rápidas.\n",
    "        \"\"\" \n",
    "        self.memory.add(\"user\", user_input)\n",
    "        response = self._client.models.generate_content(\n",
    "            model=CHAT_MODEL,\n",
    "            contents=self._messages_to_contents(self.memory.as_messages()),\n",
    "            config=types.GenerateContentConfig(\n",
    "                system_instruction=self._personalized_system_prompt(),\n",
    "                max_output_tokens=MAX_OUTPUT_TOKENS,\n",
    "                temperature=TEMPERATURE,\n",
    "            ),\n",
    "        )\n",
    "        reply = response.candidates[0].content.parts[0].text\n",
    "        self.memory.add(\"model\", reply)\n",
    "        return reply\n",
    "\n",
    "    # ── Helpers privados ──────────────────────────────────────────────────────\n",
    "\n",
    "    def _personalized_system_prompt(self) -> str:\n",
    "        return f\"{self.SYSTEM_PROMPT}\\n\\nPeriódico: {self.newspaper_name}. Región: {self.region}.\"\n",
    "\n",
    "    def _build_prompt(\n",
    "        self,\n",
    "        query: str,\n",
    "        context_snippets: list[str],\n",
    "        trending: list[str],\n",
    "        web_results: list[dict],\n",
    "    ) -> str:\n",
    "        ctx_block = \"\\n\".join(f\"- {s[:300]}\" for s in context_snippets) or \"Sin contexto previo.\"\n",
    "        trend_block = \", \".join(trending[:5]) or \"No disponible.\"\n",
    "        web_block = \"\\n\".join(\n",
    "            f\"• {r['title']} ({r['source']}): {r['snippet'][:200]}\"\n",
    "            for r in web_results\n",
    "        ) or \"Sin resultados web.\"\n",
    "\n",
    "        return f\"\"\"\n",
    "CONSULTA DE INVESTIGACIÓN: {query}\n",
    "\n",
    "CONTEXTO HISTÓRICO DEL PERIÓDICO (RAG):\n",
    "{ctx_block}\n",
    "\n",
    "TEMAS EN TENDENCIA HOY:\n",
    "{trend_block}\n",
    "\n",
    "NOTICIAS RECIENTES EN LA WEB:\n",
    "{web_block}\n",
    "\n",
    "Con base en toda la información anterior, propón 3 ideas de artículos\n",
    "para {self.newspaper_name}. Responde en el formato JSON indicado.\n",
    "\"\"\".strip()\n",
    "\n",
    "    def _messages_to_contents(self, messages: list[dict]) -> list[types.Content]:\n",
    "        result = []\n",
    "        for m in messages:\n",
    "            role = \"user\" if m[\"role\"] == \"user\" else \"model\"\n",
    "            result.append(\n",
    "                types.Content(\n",
    "                    role=role,\n",
    "                    parts=[types.Part.from_text(text=m[\"content\"])],\n",
    "                )\n",
    "            )\n",
    "        return result\n",
    "\n",
    "    def _parse_ideas(self, raw_text: str) -> list[ArticleIdea]:\n",
    "        \"\"\"Extrae ArticleIdea[] del JSON que devuelve Gemini.\"\"\"\n",
    "        try:\n",
    "            # Limpia posibles bloques markdown ```json ... ```\n",
    "            clean = raw_text.strip()\n",
    "            if clean.startswith(\"```\"):\n",
    "                clean = clean.split(\"```\")[1]\n",
    "                if clean.startswith(\"json\"):\n",
    "                    clean = clean[4:]\n",
    "            data = json.loads(clean)\n",
    "            ideas_raw = data.get(\"article_ideas\", [])\n",
    "            return [\n",
    "                ArticleIdea(\n",
    "                    title=i.get(\"title\", \"Sin título\"),\n",
    "                    angle=i.get(\"angle\", \"\"),\n",
    "                    category=i.get(\"category\", \"general\"),\n",
    "                    local_relevance_score=float(i.get(\"local_relevance_score\", 0.5)),\n",
    "                    sources=i.get(\"sources\", []),\n",
    "                    keywords=i.get(\"keywords\", []),\n",
    "                    priority=i.get(\"priority\", \"media\"),\n",
    "                )\n",
    "                for i in ideas_raw\n",
    "            ]\n",
    "        except (json.JSONDecodeError, KeyError, TypeError):\n",
    "            # Si Gemini no devuelve JSON válido → idea genérica de fallback\n",
    "            return [\n",
    "                ArticleIdea(\n",
    "                    title=\"Investigación pendiente de parseo\",\n",
    "                    angle=raw_text[:200],\n",
    "                    category=\"general\",\n",
    "                    local_relevance_score=0.5,\n",
    "                    priority=\"baja\",\n",
    "                )\n",
    "            ]"
   ]
  }
 ],
 "metadata": {
  "environment": {
   "kernel": "conda-base-py",
   "name": "workbench-notebooks.m139",
   "type": "gcloud",
   "uri": "us-docker.pkg.dev/deeplearning-platform-release/gcr.io/workbench-notebooks:m139"
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel) (Local)",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
